### ISSUE TITLE
Has this shipped in sdk?

### ISSUE THREAD

**Issue by Noitidart** [mozilla/oauthorizer#9]
Has this shipped with the Firefox official builds yet? It's good. I was hoping to use it in my non-sdk addons but cant find the jsm/js file to import. Didn't want to copy paste from here but will do if it hasnt shipped yet.

**Comment by mixedpuppy** [comment]
This was never meant to be official code in firefox, it was used for some experiments several years ago.  Happy to accept pull requests to update it if necessary.

**Comment by Noitidart** [comment]
Ah ok this is still real cool, thanks very much! :)

Do you think they may do some official stuff though to make it easy. As with WebExtAPI i think that's their goal they want to make things doable by newbies.
